### ISSUE TITLE
Gap in the footer

### ISSUE THREAD

**Issue by CatherineIles** [kentcc/ebbsfleet#2]
There's a gap in the footer links (see screen shot) which is a bit odd but no showstopper!

Please can you also email me where I can edit the footer links as some of these aren't needed. Thanks.

**Comment by CharlesCarnell** [comment]
Can you try re-attaching a screenshot to this issue?

**Comment by CatherineIles** [comment]
The gap is appearing on the live site. It looks like this on my machine

Catherine Iles | Digital Services | Kent County Council | External: 03000 416292 | Internal: 416292 | www.kent.gov.uk<http://www.kent.gov.uk/> | @kent_cc<http://www.twitter.com/kent_cc>

**Comment by CatherineIles** [comment]
The gap is appearing on the live site. It looks like this on my machine:

[cid:image001.png@01D060DF.5FB33D20]

Catherine Iles | Digital Services | Kent County Council | External: 03000 416292 | Internal: 416292 | www.kent.gov.uk<http://www.kent.gov.uk/> | @kent_cc<http://www.twitter.com/kent_cc>

**Comment by CharlesCarnell** [comment]
Github Issues doesn't appear to accept images sent over email, you'll have to drag and drop it into the comment field on the site instead of responding to the email.

**Comment by CatherineIles** [comment]
If you go to the site, you can see the gap. I’m just deleting some of the footers so it might sort itself out…

Catherine Iles | Digital Services | Kent County Council | External: 03000 416292 | Internal: 416292 | www.kent.gov.uk<http://www.kent.gov.uk/> | @kent_cc<http://www.twitter.com/kent_cc>

**Comment by CharlesCarnell** [comment]
For reference, the gap referred to was the space between the two footer menu lists.

![screen shot 2015-03-18 at 11 41 20](https://cloud.githubusercontent.com/assets/10024311/6707943/d5eb9c62-cd63-11e4-9dce-eb1b6ad09fc7.png)

After a discussion with @natmunckton, this has been removed from the WordPress build.
